### ISSUE TITLE
Update AGI definition

### ISSUE THREAD

**Issue by CT126** [Zoobdude/Digital-Production-T-Lvl-Flashcards#1]
Update: "A clever AI that has can think for itself, however it doesn't know very much about humans." 

to

"An autonomous and intelligent AI with the ability to think independently, but lacking comprehensive knowledge about humans."

**Comment by PizzaCat8** [comment]
Sorry Zoobdude, will make a more logical and meaningful title in the next pull request. 

![images](https://github.com/Zoobdude/Digital-Production-T-Lvl-Flashcards/assets/144335553/6cb9fe62-762b-4ba6-9669-fb266aaf36f9)
